# Generated by Django 4.1.3 on 2022-12-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_memory_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
